### ISSUE TITLE
Make chat look nicer

### ISSUE THREAD

**Issue by kvnneff** [kvnneff/bloxparty#25]
- If its possible the chat log should be more obviously a chat log even when its empty.
- The chat input needs to be made more obvious as well

**Comment by G07cha** [comment]
Prompt(">" symbol) looks strange, maybe replace it with "Enter message here" for example?
![screen shot 2015-11-03 at 5 50 57 pm](https://cloud.githubusercontent.com/assets/6943514/10912739/7664e0b4-8253-11e5-8f99-934f2792b225.png)

**Comment by kvnneff** [comment]
Agreed.  I originally had a message in there but when there's not much other text on screen it was a little overbearing.  But something should be done.

**Comment by G07cha** [comment]
Also chat boxes have square angles, when other have a bit rounded.
![screen shot 2015-11-03 at 6 02 58 pm](https://cloud.githubusercontent.com/assets/6943514/10913130/4a427c2e-8255-11e5-9505-ebde7d84357c.png)

**Comment by kvnneff** [comment]
I've restyled the chat panes to look nicer but still need to clean up the css.

**Comment by kvnneff** [comment]
Done.
