### ISSUE TITLE
Incorrect view in Safari

### ISSUE THREAD

**Issue by G07cha** [kvnneff/bloxparty#32]
### Chrome

![screen shot 2015-11-07 at 10 35 34 am](https://cloud.githubusercontent.com/assets/6943514/11014366/949eb92a-853b-11e5-8ad6-57cc75ddf54e.png)
### Safari

![screen shot 2015-11-07 at 10 34 36 am](https://cloud.githubusercontent.com/assets/6943514/11014363/8b102312-853b-11e5-8c79-0e2e8cff9d60.png)

**Comment by kvnneff** [comment]
This has been fixed in the recent commits.
