### ISSUE TITLE
Log out button don't have any actions

### ISSUE THREAD

**Issue by G07cha** [kvnneff/bloxparty#5]
First of all, better to hide this button on login screen i think(becouse user don't even logged in).
After investigating source code I've noticed that button don't have action for now so if you don't mind I would like to keep this issue open until logout action will be implemented.

**Comment by G07cha** [comment]
@kvnneff, Logout button doesn't have any actions, I think would be good if click on "Logout" close application because for now bloxparty don't have any exit buttons in new design.

**Comment by kvnneff** [comment]
The Logout button should disconnect you from the server you're playing on, with the idea being that eventually maybe there will be many servers people can play on.

You're right, though, that there is no obvious exit button.  I'll start a new issue for that.

**Comment by G07cha** [comment]
For now logout button don't work at all(don't disconnection from server) on OS X
