### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by G07cha** [kvnneff/bloxparty#9]
What about create `gh-pages` branch and start building landing website with download section? This will attract non-technician people that don't know about/how to use GitHub. I'm ready to participate in website development.

**Comment by kvnneff** [comment]
A website would be great!

I'm working long hours on a farm over the next few weeks so updates may be slow from me.  If you wanted to get the website going that'd be really cool.  I added you as a collaborator so you can push to `gh-pages` as you see fit.

Thanks for helping out!

**Comment by G07cha** [comment]
Thank for your trust, I'll try to do my best.

**Comment by G07cha** [comment]
I've done early prototype, check this out: http://kvnneff.github.io/bloxparty/
If you have any thoughts or suggestions I would like to hear them.

**Comment by kvnneff** [comment]
Looks good to me so far!

One thing I was thinking is that BloxParty doesn't need Electron to work, it's entirely browser compatible so it'd be cool if people could play it on the website.

That would require running `npm run build-ui` in the master branch and grabbing `build/index.js` and `build/index.css` and putting them into the `gh-pages` branch.  I really need to clean up the css first though so we shouldn't worry about it right now I think, just something to keep in mind.

**Comment by G07cha** [comment]
Sure it's easy to add one more page + button on main page. I'm going to finish download page tomorrow. Also want to notice that site requires specific name specifications in release binaries. Binary must contain only one of listed words: `win32, darwin, linux` and also have `-x64` or `-ia32` after it for Downloads page. All specifications correct in latest release(1.1) so I just leave it for future releases.

**Comment by G07cha** [comment]
Finished custom downloads page and migrated to custom domain http://bloxparty.tk/
Should we add website to repo description(on top)?

**Comment by G07cha** [comment]
It's also mobile friendly

![screenshot_2015-10-28-19-44-18](https://cloud.githubusercontent.com/assets/6943514/10798160/ed0f2f2a-7dae-11e5-9d06-9851a33a8dcb.png)

**Comment by G07cha** [comment]
I think it's enough to close this issue, I will make few more website updates tomorrow but they are minor. When you finish cleaning up css just create another issue for it.
